import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import MobileHeader from "./components/lab/MobileHeader";
import Header from "./components/lab/Header";
import { Suspense } from "react";
import PulseDashboard from "./components/lab/PulseDashboard";
import LoginButtonContainer from "./components/lab/LoginButtonContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['cyrillic', 'latin'],
})
const jetBrainsMono = JetBrains_Mono({
  variable: '--font-jetBrains-mono',
  subsets: ['cyrillic', 'latin']
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${jetBrainsMono.variable} ${montserrat.variable} h-full antialiased`}
    >
      <body className=" h-dvh  flex flex-col lg:h-dvh p-1">
        <Suspense fallback={<div>Loading...</div>}>
          <Header />
          <MobileHeader statusSlot={<PulseDashboard />} loginSlot={<LoginButtonContainer />} />
        </Suspense>
        {children}
      </body>

    </html>

  );
}
