import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import MobileHeader from "./components/lab/MobileHeader";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['cyrillic', 'latin'],
})
const jetBrainsMono = JetBrains_Mono({
  variable: '--font-jetBrains-mono',
  subsets: ['cyrillic', 'latin']
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}${jetBrainsMono.variable}${montserrat.variable} h-full antialiased`}
    >

      <body className="debug-cyan h-dvh overflow-hidden flex flex-col md:h-dvh p-2">
        <Suspense fallback={<div className="h-14 bg-black" />} >
          <MobileHeader />
        </Suspense>
        <Suspense fallback={<div className="flex-1 flex items-center justify-center text-amber-500 font-mono">Loading laboratory console...</div>}>
          {children}
        </Suspense>
      </body>

    </html>

  );
}
