import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import MobileHeader from "./components/lab/MobileHeader";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['cyrillic', 'latin'],
})
const jetBrainsMono = JetBrains_Mono({
  variable: '--font-jetBrains-mono',
  subsets: ['cyrillic', 'latin']
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}${jetBrainsMono.variable}${montserrat.variable} h-full antialiased`}
    >

      <Suspense>
        <body className="min-h-full flex flex-col">
          <MobileHeader />{children}</body>
      </Suspense>

    </html>

  );
}
